//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp5.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Export
    {
        public int Id { get; set; }
        public string Pharmacy_Code { get; set; }
        public string Product_Code { get; set; }
        public int Quantity { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Pharmacy Pharmacy { get; set; }
        public virtual Product Product { get; set; }
    }
}
